version: "3.7"

services:
  db:
    image: mysql:5.7
    container_name: "naditok-db"
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: naditok
    volumes:
      - "./.docker/mysql/db:/var/lib/mysql"
    ports:
      - 3306:3306
      - 33060:33060

  adminer:
    image: adminer
    container_name: "naditok-adminer"
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  php:
    image: php:7.4-fpm
    container_name: "naditok-php"
    working_dir: "/var/www/"
    volumes:
      - "./:/var/www/"
      - "./docker/php/custom.php.ini:/usr/local/etc/php/custom.d/custom.ini"
    environment:
      PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
    ports:
      - "9000:9000"
    depends_on:
      - db
    command: /bin/sh -c "apt-get update && apt-get upgrade -y && apt-get install -y git libzip-dev && docker-php-ext-install zip pdo pdo_mysql&& bin/install.sh && php-fpm "

  nginx:
    image: nginx:alpine
    container_name: "naditok-nginx"
    working_dir: "/var/www/"
    volumes:
      - "./:/var/www/"
      - "./.docker/nginx/localhost.conf:/etc/nginx/conf.d/localhost.template"
    command: /bin/sh -c "cp /etc/nginx/conf.d/localhost.template /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    depends_on:
      - php
    ports:
      - "80:80"
